name: blockchaintracking

type: rails

up:
  - homebrew:
    - openssl
    - shopify/shopify/mysql-client:
        or:        [mysql]
        conflicts: [mysql-connector-c]
    # - another_package
  - ruby: 2.4.3
  - node:
      yarn: true
      version: v8.9.4
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: blockchaintracking.railgun
      user: root
      password: ''
      database: blockchaintracking_development

server:
  port: 58761

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run:    bin/rails test

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  "My Application": https://blockchaintracking.myshopify.io
