default: &default
 adapter: mysql2
 pool: 5
 timeout: 5000
 encoding: utf8

development:
 <<: *default
 database: blockchaintracking_development
 host: blockchaintracking.railgun
 strict: false
 port: 3306
 username: root
 password:

test:
 <<: *default
 database: blockchaintracking_test
 host: blockchaintracking.railgun
 strict: false
 port: 3306
 username: root
 password:

production:
 <<: *default
